%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.4 (R2018a) and Database Toolbox Version 8.1 on 17-May-2020 16:24:57

%% Set preferences
prefs = setdbprefs('DataReturnFormat');
setdbprefs('DataReturnFormat','table')

%% Make connection to database
conn = database('MySQL','vrk','');

%% Execute query and fetch results
curs = exec(conn,['SELECT DISTINCT ' ...
    'snr_h03.id, ' ...
    'snr_h03.rec_date, ' ...
    '`snr_h03.mka82.ct001.xq01`.`value` AS "s1",' ... #StatorColdAirTemp1
    '`snr_h03.mka82.ct002.xq01`.`value` AS "s2"' ... #StatorColdAirTemp2
    'FROM ' ...
    'snr_h03 ' ...
    'INNER JOIN `snr_h03.mka82.ct001.xq01` ON snr_h03.id = `snr_h03.mka82.ct001.xq01`.id ' ...
    'INNER JOIN `snr_h03.mka82.ct002.xq01` ON snr_h03.id = `snr_h03.mka82.ct002.xq01`.id ' ...
    'WHERE ' ...
    'snr_h03.id > 100000 ' ...
    'LIMIT 500']);
curs = fetch(curs);
data = curs.Data;

% ts = data.id;
s1 = data.s1;
s2 = data.s2;
time = .02*(1:500)';
s1_ts = timetable(seconds(time), s1);
s2_ts = timetable(seconds(time), s2);
close(curs)

%% Close connection to database
close(conn)

%% Restore preferences
setdbprefs('DataReturnFormat',prefs)

%% Clear variables
clear prefs conn curs